name: "Csharpier dotnet 8"
on:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize
jobs:
  format:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - name: Print pull_request event
        run: |
          echo Branch:
          echo "${{ github.event.pull_request }}"

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Provisioned automatically by GitHub
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'  #

      - name: Cache Csharpier tool
        id: cache-csharpier
        uses: actions/cache@v3
        with:
          path: ~/.dotnet/tools
          key: ${{ runner.os }}-dotnet-tools-csharpier

      - name: Install Csharpier if not cached
        run: dotnet tool install -g csharpier || echo "Csharpier already installed"

      - name: Run Csharpier
        run: dotnet csharpier . 

      - name: Check for formatting changes
        run: |
          if [[ `git status --porcelain` ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add .
            if [[ `git status --porcelain` ]]; then
              git commit -m "Apply Csharpier code formatting"
              git push
            else 
              echo "No formatting changes needed"
            fi
          else
            echo "No formatting changes needed"
          fi
