name: "[net8] deploy nts-nexus-test-windows"
on:
  push:
    branches:
    - feature/azure-function-poc
env:
  AZURE_FUNCTIONAPP_NAME: nts-nexus-test-windows
  AZURE_FUNCTIONAPP_PACKAGE_PATH: Nexus\NTS.Nexus.Test\published
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 8.0.x
  WORKING_DIRECTORY: src/Nexus\NTS.Nexus.Test
#   DOTNET_CORE_VERSION_INPROC: 6.0.x
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
    # - name: Setup .NET Core (for inproc extensions)
    #   uses: actions/setup-dotnet@v1
    #   with:
    #     dotnet-version: ${{ env.DOTNET_CORE_VERSION_INPROC }}
    #     include-prerelease: True

    #Slap on top of every build: see https://github.com/Not-Endurance/not-timing-system/issues/361
    - name: Set current workding directory env
      run: echo "CURRENT_DIR=$(Get-Location)\src" | Out-File -FilePath $env:GITHUB_ENV -Append

    - name: Test Github env
      run: |
       echo ${{ env.CURRENT_DIR }} 
       echo $CURRENT_DIR

    - name: Remove local-cache NuGet source
      run: dotnet nuget remove source "local-cache" --configfile ./src/NuGet.config

    - name: Restore
      run: dotnet restore "${{ env.WORKING_DIRECTORY }}" -property:SolutionDir="src"

    - name: Build
      run: dotnet build "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-restore -property:SolutionDir="src"

    - name: Publish
      run: dotnet publish "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}" -property:SolutionDir="./src"

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: functionapp
        path: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}

  deploy:
    runs-on: windows-latest
    needs: build
    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: functionapp
        path: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}

    - name: Deploy to Azure Function App
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        publish-profile: ${{ secrets.NTS_NEXUS_TEST_WINDOWS_A03C }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
