name: "[net8] Test Judge"

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  test-judge:
    runs-on: ubuntu-latest

    env:
      TEST_PROJECT_PATH: ./tests/NTS.Judge.Tests
      SOURCE_SOLUTION_PATH: "{pwd}/src"

    steps:
      - name: Set current workding directory env
        run: echo "CURRENT_DIR=$(pwd)/src" >> $GITHUB_ENV

      # Step 1: Check out the repository code
      - name: Check out code
        uses: actions/checkout@v3

      # Step 2: Set up .NET (adjust version as needed)
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      # Necessary bacause dotnet restore fails otherwise
      - name: Remove local-cache NuGet source
        run: dotnet nuget remove source "local-cache" --configfile ./src/NuGet.config

      # Step 3: Restore dependencies for the entire solution/project
      - name: Restore
        run: dotnet restore ${{ env.TEST_PROJECT_PATH }}

      # Step 4: Build the solution in Release mode (optional, but recommended)
      - name: Build
        run: dotnet build ${{ env.TEST_PROJECT_PATH }} -property:SolutionDir="$CURRENT_DIR" --configuration Release --no-restore

      - name: Test
        run: dotnet test ${{ env.TEST_PROJECT_PATH }} -property:SolutionDir="$CURRENT_DIR" --configuration Release --no-build
