name: Test Judge

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      TEST_PROJECT_PATH: ./tests/NTS.Judge.Tests

    steps:
      # Step 1: Check out the repository code
      - name: Check out code
        uses: actions/checkout@v3

      # Step 2: Set up .NET (adjust version as needed)
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Remove local-cache NuGet source
        run: dotnet nuget remove source "local-cache" --configfile ./src/NuGet.config

      # Step 3: Restore dependencies for the entire solution/project
      - name: Restore
        run: dotnet restore ${{ env.TEST_PROJECT_PATH }}

      # Step 4: Build the solution in Release mode (optional, but recommended)
      - name: Build
        run: dotnet build ${{ env.TEST_PROJECT_PATH }} -property:SolutionDir='.' --configuration Release --no-restore

      # Step 5: Run tests
      - name: Test
        run: dotnet test ${{ env.TEST_PROJECT_PATH }} -property:SolutionDir='.' --configuration Release --no-build
